version: 2

sources:
  - name: raw
    schema: public
    tables:
      - name: raw_customers
      - name: raw_products
      - name: raw_orders
      - name: raw_order_items

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests: [unique, not_null]
      - name: email
        tests: [unique, not_null]

  - name: stg_orders
    columns:
      - name: order_id
        tests: [unique, not_null]
      - name: customer_id
        tests: [not_null]

  - name: stg_products
    columns:
      - name: product_id
        tests: [unique, not_null]

  - name: stg_order_items
    columns:
      - name: item_id
        tests: [unique, not_null]
      - name: order_id
        tests: [not_null]
      - name: product_id
        tests: [not_null]
